config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get 'welcome/index'
  devise_for :users
  root to: 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark">
  <% if user_signed_in? %>
  <p class="navbar-brand"><%= current_user[:email] %>'s Notes</p>
  <%= button_to "Log Out", destroy_user_session_path, class:"btn btn-warning", :method => :delete %>
  <% else %>
  <p class="navbar-brand">Login To See Your Notes</p>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Snote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :note_title %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :note_body %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit Current Note</h1>

<%= render 'form', note: @note %>
<table>
<tr>
<td><%= button_to 'Show', @note, class:"btn btn-info", method: :get %></td>
<td><%= button_to 'Back', notes_path, class:"btn btn-danger", method: :get %></td>
</tr>
</table>

app/views/notes/index.html.erb
<div>
<table class="table table-dark">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <% if note.user_id == current_user[:id] %>
      <tr>
          <td><%= note.title %></td>
          <td><%= note.body %></td>
          <td><%= note.user.email %></td>
          <td><%= button_to 'Show', note, class:"btn btn-info", method: :get %></td>
          <td><%= button_to 'Edit', edit_note_path(note), class:"btn btn-primary", method: :get %></td>
          <td><%= button_to 'Destroy', note, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
</div>
<%= button_to 'New Note', new_note_path, class:"btn btn-success", method: :get %>

app/views/notes/new.html.erb
<h1>Create New Note</h1>

<%= render 'form', note: @note %>

<%= button_to 'Back', notes_path, class:"btn btn-danger", method: :get %>

app/views/notes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user.email %>
</p>
<table>
<tr>
<td><%= button_to 'Edit', edit_note_path(@note), class:"btn btn-primary", method: :get %></td>
<td><%= button_to 'Back', notes_path, class:"btn btn-danger", method: :get %></td>
</tr>
</table>

app/views/welcome/index.html.erb
<h1>Welcome</h1>